### 00 LIBRERIAS

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from glob import glob
# Aplicar configuraciones de visualización total de Pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

from pathlib import Path
import glob

import warnings
warnings.filterwarnings("ignore")
import plotly.express as px

import func_negocio as func

### 01 EXTRACT

In [ ]:
df_ventas = pd.read_parquet(r"output\VentasReal.parquet")
df_jeq = pd.read_parquet(r"output\JEq.parquet")

In [ ]:
df_jeq.head(3)

,_Periodo,codigo_local,_Tienda,_Tipo,_GrupoArea,HRS_REAL,JEq
0,202401,1198,1198_Cusco Wanchaq - PVH,ABARROTES,ABARROTES,1339.48,6.301317
1,202401,1198,1198_Cusco Wanchaq - PVH,ALMACEN,ALMACEN,724.75,3.409442
2,202401,1198,1198_Cusco Wanchaq - PVH,ALMACEN FRESCOS,ALMACEN FRESCOS,671.73,3.160020

In [ ]:
df_ventas.head(3)

,_Tienda,Anio,NroMes,_Tipo,Vta.,VtaUn.,VtaPpto.,_Periodo
0,1198_Cusco Wanchaq - PVH,2025.0,1.0,ELECTRO,322505.89,5515.0,282966.2542,202501
1,1198_Cusco Wanchaq - PVH,2025.0,2.0,ELECTRO,201833.95,3794.0,260530.5531,202502
2,1198_Cusco Wanchaq - PVH,2025.0,3.0,ELECTRO,282532.99,12218.0,356292.4920,202503

In [ ]:
# df_ventas["_Periodo"] = df_ventas["_Periodo"].astype(str)
# df_ventas["_Tipo"] = ( df_ventas["_Tipo"].astype(str).str.upper().str.normalize("NFKD").str.encode("ascii", errors="ignore").str.decode("utf-8"))
# df_jeq["_Periodo"] = df_jeq["_Periodo"].astype(str)
# df_jeq["_Tipo"] = ( df_jeq["_Tipo"].astype(str).str.upper().str.normalize("NFKD").str.encode("ascii", errors="ignore").str.decode("utf-8"))

df_prod = df_ventas.merge(df_jeq[["_Periodo", "_Tienda", "_Tipo", "JEq"]], on = ["_Periodo", "_Tienda", "_Tipo"], how="left")

In [ ]:
df_jeq[(df_jeq["_Tienda"]=="1198_Cusco Wanchaq - PVH")&(df_jeq["_Periodo"]=="202601")]

,_Periodo,codigo_local,_Tienda,_Tipo,_GrupoArea,HRS_REAL,JEq
18325,202601,1198,1198_Cusco Wanchaq - PVH,ABARROTES,ABARROTES,1709.55,8.042238
18326,202601,1198,1198_Cusco Wanchaq - PVH,ALMACEN,ALMACEN,881.93,4.148864
18327,202601,1198,1198_Cusco Wanchaq - PVH,ALMACEN FRESCOS,ALMACEN FRESCOS,407.21,1.915638
18328,202601,1198,1198_Cusco Wanchaq - PVH,Adm,ADM,1017.89,4.788461
18329,202601,1198,1198_Cusco Wanchaq - PVH,CAJAS,CAJAS,3381.25,15.906418
18330,202601,1198,1198_Cusco Wanchaq - PVH,ELECTRO,ELECTRO,444.08,2.089086
18331,202601,1198,1198_Cusco Wanchaq - PVH,FRESCOS,FRESCOS,1159.05,5.452520
18332,202601,1198,1198_Cusco Wanchaq - PVH,INVENTARIOS,INVENTARIOS,191.96,0.903038

In [ ]:
df_prod["Prod."] = df_prod["Vta."] / df_prod["JEq"]
df_prod[(df_prod["_Tienda"]=="1198_Cusco Wanchaq - PVH")&(df_prod["_Periodo"]=="202601")]

,_Tienda,Anio,NroMes,_Tipo,Vta.,VtaUn.,VtaPpto.,_Periodo,JEq,Prod.
12,1198_Cusco Wanchaq - PVH,2026.0,1.0,ELECTRO,223604.71,18977.00,2.610227e+05,202601,2.089086,1.070347e+05
2018,1198_Cusco Wanchaq - PVH,2026.0,1.0,FRESCOS,640460.38,87573.78,4.344146e+05,202601,5.452520,1.174614e+05
4027,1198_Cusco Wanchaq - PVH,2026.0,1.0,ALMACEN FRESCOS,640460.38,87573.78,4.344146e+05,202601,1.915638,3.343326e+05
6036,1198_Cusco Wanchaq - PVH,2026.0,1.0,ABARROTES,1859223.11,241093.00,1.641772e+06,202601,8.042238,2.311823e+05
8047,1198_Cusco Wanchaq - PVH,2026.0,1.0,CAJAS,2653501.35,347440.78,2.257510e+06,202601,15.906418,1.668195e+05
10057,1198_Cusco Wanchaq - PVH,2026.0,1.0,RECEPCION,2723288.20,347643.78,2.337209e+06,202601,NaN,NaN
12069,1198_Cusco Wanchaq - PVH,2026.0,1.0,ALMACEN,2082827.82,260070.00,1.902795e+06,202601,4.148864,5.020236e+05
14081,1198_Cusco Wanchaq - PVH,2026.0,1.0,INVENTARIOS,2082827.82,260070.00,1.902795e+06,202601,0.903038,2.306468e+06
16093,1198_Cusco Wanchaq - PVH,2026.0,1.0,MULTIFUNCIONAL,2723288.20,347643.78,2.337209e+06,202601,NaN,NaN