librerias

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from glob import glob
# Aplicar configuraciones de visualización total de Pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

from pathlib import Path
import glob

import warnings
warnings.filterwarnings("ignore")
import plotly.express as px

import func_negocio as func

extract

In [9]:
lista_excel = ["Dotación_FRET_202507.xlsx","Dotación_FRET_202508.xlsx", "Dotación_FRET_202509.xlsx", "Dotación_FRET_202510.xlsx", "Dotación_FRET_202511.xlsx",
               "Dotación_FRET_202512.xlsx", "Dotación_FRET_202601.xlsx", "Dotación_FRET_202602.xlsx", "Dotación_FRET_202603.xlsx", "Dotación_FRET_202604.xlsx", "Dotación_FRET_202605.xlsx", "Dotación_FRET_202606.xlsx"]
ruta = r"input\bd_dotacion"

In [14]:
df_dotacion_2024 = pd.read_excel(r"input\bd_dotacion\bk_Dotacion202401_202506.xlsx")

In [26]:
rutas_completas = [os.path.join(ruta, archivo) for archivo in lista_excel]

# 2. Leer los DataFrames manteniendo la compresión de listas
dfs = [
    pd.read_excel(p, sheet_name="Detail_Capo", header=1) for p in rutas_completas
]

# 3. Concatenar usando 'keys' para inyectar el nombre del archivo (operación nativa en C)
df_dotacion = pd.concat(dfs, keys=lista_excel, ignore_index=False)

# 4. Pasar el nombre del archivo del índice a una columna y limpiar el MultiIndex
df_dotacion = df_dotacion.reset_index(level=0).rename(
    columns={"level_0": "Nombre_Archivo"}
)
df_dotacion = df_dotacion.reset_index(drop=True)

In [15]:
df_dotacion_2024

,Tipo dotación,Formato,Ubicación,Departamento,Nombre de Posición,Categoría,Ceco,Name,Date modified,Fecha,TipoDotacion,HeadCount,codigo_local,Depa_HCM
0,Ordinaria,Plaza Vea,Fret Pvea Acho,E-Commerce Virtual,Repres. De Servicios Ecommerce,Operativo,Tienda virtual,Dotación_FRET_202406.xlsx,2025-07-08 11:31:34,2024-06-01,RealFT,1.0,P159,Fret - Pvea Acho
1,Ordinaria,Plaza Vea,Fret Pvea Acho,E-Commerce Virtual,Coordinador De Despacho,Medio,Tienda virtual,Dotación_FRET_202406.xlsx,2025-07-08 11:31:34,2024-06-01,TeoFT,1.0,P159,Fret - Pvea Acho
2,Ordinaria,Plaza Vea,Fret Pvea Acho,E-Commerce Virtual,Coordinador De Despacho,Medio,Tienda virtual,Dotación_FRET_202406.xlsx,2025-07-08 11:31:34,2024-06-01,RealFT,1.0,P159,Fret - Pvea Acho
3,Ordinaria,Plaza Vea,Fret Pvea Acho,E-Commerce Virtual,Coordinador De Despacho,Medio,Tienda virtual,Dotación_FRET_202402.xlsx,2025-07-01 21:26:24,2024-02-01,TeoFT,1.0,P159,Fret - Pvea Acho
4,Ordinaria,Plaza Vea,Fret Pvea Acho,E-Commerce Virtual,Coordinador De Despacho,Medio,Tienda virtual,Dotación_FRET_202402.xlsx,2025-07-01 21:26:24,2024-02-01,RealFT,1.0,P159,Fret - Pvea Acho
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134604,Ordinaria,Plaza Vea,Pvo - Tarapoto,Sala Frescos,Jefe De Seccion,Medio,Operaciones Tienda,Dotación_FRET_202401.xlsx,2025-06-11 19:11:03,2024-01-01,RealFT,1.0,SO05,Spo - Pvo Tarapoto
134605,Ordinaria,Plaza Vea,Pvo - Tarapoto,Sala Frescos,Repres. De Servicios 5X2 1Er Turno,Operativo,Operaciones Tienda,Dotación_FRET_202506.xlsx,2025-07-11 10:12:24,2025-06-01,TeoPT,2.0,SO05,Spo - Pvo Tarapoto
134606,Ordinaria,Plaza Vea,Pvo - Tarapoto,Sala Frescos,Repres. De Servicios 5X2 1Er Turno,Operativo,Operaciones Tienda,Dotación_FRET_202506.xlsx,2025-07-11 10:12:24,2025-06-01,RealPT,2.0,SO05,Spo - Pvo Tarapoto
134607,Ordinaria,Plaza Vea,Pvo - Tarapoto,Sala Frescos,Repres. De Servicios Polleria 5X2,Operativo,Operaciones Tienda,Dotación_FRET_202506.xlsx,2025-07-11 10:12:24,2025-06-01,TeoPT,2.0,SO05,Spo - Pvo Tarapoto
134608,Ordinaria,Plaza Vea,Pvo - Tarapoto,Sala Frescos,Repres. De Servicios Polleria 5X2,Operativo,Operaciones Tienda,Dotación_FRET_202506.xlsx,2025-07-11 10:12:24,2025-06-01,RealPT,2.0,SO05,Spo - Pvo Tarapoto

In [16]:
df_dotacion_2024.columns

Index(['Tipo dotación', 'Formato', 'Ubicación', 'Departamento',
       'Nombre de Posición', 'Categoría', 'Ceco', 'Name', 'Date modified',
       'Fecha', 'TipoDotacion', 'HeadCount', 'codigo_local', 'Depa_HCM'],
      dtype='object')

In [43]:
df_dotacion

,Nombre_Archivo,Art_3,Art_2,Art_1,Tipo dotación,Formato,Ubicación,Depa_HCM,Departamento,Nombre de Posición,Dotación Teórica Full,Dotación Teórica Part,Dotación Teórica Total,Dotación Real Full,Dotación Real Part,Dotación Real Total,Diferencia Full,Diferencia Part,Diferencia Total,Vulnerables Full,Vulnerables Part,Vulnerables Total,Gap Real Full,Gap Real Part,Gap Real Total,Ubicación.1,Categoría,Responsable,Status,REGION,ZONA // PUESTO,DISTRITIO,Fecha,Cluster,Formato Tienda,Ceco,JEQ Teórico,JEQ Real,JEQ Diferencia,Stand By Full,Stand By Part
0,Dotación_FRET_202507.xlsx,Fret - Pvea Acho - AdministracionAsistente De TiendaOrdinariaActiva,Fret - Pvea Acho - AdministracionAsistente De TiendaOrdinaria,Fret - Pvea Acho - AdministracionAsistente De Tienda,Ordinaria,Plaza Vea,Fret Pvea Acho,Fret - Pvea Acho,Administracion,Asistente De Tienda,1.0,0,1.0,1,0,1,0.0,0,0.0,0,0,0,0,0,0,Lima,Medio,Rodolfo Olivry,Activa,Sebastian Santangelo,0,0,2020-12-22 00:00:00,C2,Hiper,Operaciones Tienda,1.0,1.0,0.0,NaN,NaN
1,Dotación_FRET_202507.xlsx,Fret - Pvea Acho - AdministracionGerente De TiendaOrdinariaActiva,Fret - Pvea Acho - AdministracionGerente De TiendaOrdinaria,Fret - Pvea Acho - AdministracionGerente De Tienda,Ordinaria,Plaza Vea,Fret Pvea Acho,Fret - Pvea Acho,Administracion,Gerente De Tienda,1.0,0,1.0,1,0,1,0.0,0,0.0,0,0,0,0,0,0,Lima,Lider,Rodolfo Olivry,Activa,Sebastian Santangelo,0,0,2020-12-22 00:00:00,C2,Hiper,Operaciones Tienda,1.0,1.0,0.0,NaN,NaN
2,Dotación_FRET_202507.xlsx,Fret - Pvea Acho - AdministracionSubgerente De TiendaOrdinariaActiva,Fret - Pvea Acho - AdministracionSubgerente De TiendaOrdinaria,Fret - Pvea Acho - AdministracionSubgerente De Tienda,Ordinaria,Plaza Vea,Fret Pvea Acho,Fret - Pvea Acho,Administracion,Subgerente De Tienda,0.0,0,0.0,0,0,0,0.0,0,0.0,0,0,0,0,0,0,Lima,Lider,Rodolfo Olivry,Activa,Sebastian Santangelo,0,0,2020-12-22 00:00:00,C2,Hiper,Operaciones Tienda,0.0,0.0,0.0,NaN,NaN
3,Dotación_FRET_202507.xlsx,Fret - Pvea Acho - AlmacenJefe De SeccionOrdinariaActiva,Fret - Pvea Acho - AlmacenJefe De SeccionOrdinaria,Fret - Pvea Acho - AlmacenJefe De Seccion,Ordinaria,Plaza Vea,Fret Pvea Acho,Fret - Pvea Acho,Almacen,Jefe De Seccion,1.0,0,1.0,1,0,1,0.0,0,0.0,0,0,0,0,0,0,Lima,Medio,Rodolfo Olivry,Activa,Sebastian Santangelo,0,0,2020-12-22 00:00:00,C2,Hiper,Operaciones Tienda,1.0,1.0,0.0,NaN,NaN
4,Dotación_FRET_202507.xlsx,Fret - Pvea Acho - AlmacenRepres. De ServiciosOrdinariaActiva,Fret - Pvea Acho - AlmacenRepres. De ServiciosOrdinaria,Fret - Pvea Acho - AlmacenRepres. De Servicios,Ordinaria,Plaza Vea,Fret Pvea Acho,Fret - Pvea Acho,Almacen,Repres. De Servicios,0.0,0,0.0,1,0,1,1.0,0,1.0,0,0,0,0,0,0,Lima,Operativo,Rodolfo Olivry,Activa,Sebastian Santangelo,RS,0,2020-12-22 00:00:00,C2,Hiper,Operaciones Tienda,0.0,1.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57420,Dotación_FRET_202606.xlsx,PVO - Tarapoto 2 - Sala FrescosRepres. De ServiciosOrdinariaActiva,PVO - Tarapoto 2 - Sala FrescosRepres. De ServiciosOrdinaria,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios,Ordinaria,Plaza Vea,PVO Tarapoto 2,PVO - Tarapoto 2,Sala Frescos,Repres. De Servicios,8.0,0,8.0,7,0,7,-1.0,0,-1.0,0,0,0,0,0,0,Provincia,Operativo,Pepe Aramburu,Activa,Sofia Villanueva,0,0,2020-12-22 00:00:00,B3,Hiper,Operaciones Tienda,8.0,7.0,-1.0,NaN,NaN
57421,Dotación_FRET_202606.xlsx,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios 5X2OrdinariaActiva,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios 5X2Ordinaria,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios 5X2,Ordinaria,Plaza Vea,PVO Tarapoto 2,PVO - Tarapoto 2,Sala Frescos,Repres. De Servicios 5X2,0.0,0,0.0,0,1,1,0.0,1,1.0,0,0,0,0,0,0,Provincia,Operativo,Pepe Aramburu,Activa,Sofia Villanueva,0,0,2020-12-22 00:00:00,B3,Hiper,Operaciones Tienda,0.0,0.5,0.5,NaN,NaN
57422,Dotación_FRET_202606.xlsx,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios 5X2 1Er TurnoOrdinariaActiva,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios 5X2 1Er TurnoOrdinaria,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios 5X2 1Er Turno,Ordinaria,Plaza Vea,PVO Tarapoto 2,PVO - Tarapoto 2,Sala Frescos,Repres. De Servicios 5X2 1Er Turno,0.0,2,2.0,0,1,1,0.0,-1,-1.0,0,0,0,0,0,0,Provincia,Operativo,Pepe Aramburu,Activa,Sofia Villanueva,0,0,2020-12-22 00:00:00,B3,Hiper,Operaciones Tienda,1.0,0.5,-0.5,NaN,NaN
57423,Dotación_FRET_202606.xlsx,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios 5X2 2Do TurnoOrdinariaActiva,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios 5X2 2Do TurnoOrdinaria,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios 5X2 2Do Turno,Ordinaria,Plaza Vea,PVO Tarapoto 2,PVO - Tarapoto 2,Sala Frescos,Repres. De Servicios 5X2 2Do Turno,0.0,1,1.0,0,5,5,0.0,4,4.0,0,0,0,0,0,0,Provincia,Operativo,Pepe Aramburu,Activa,Sofia Villanueva,0,0,2020-12-22 00:00:00,B3,Hiper,Operaciones Tienda,0.5,2.5,2.0,NaN,NaN
57424,Dotación_FRET_202606.xlsx,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios IOrdinariaActiva,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios IOrdinaria,PVO - Tarapoto 2 - Sala FrescosRepres. De Servicios I,Ordinaria,Plaza Vea,PVO Tarapoto 2,PVO - Tarapoto 2,Sala Frescos,Repres. De Servicios I,2.0,0,2.0,3,0,3,1.0,0,1.0,0,0,0,0,0,0,Provincia,Medio,Pepe Aramburu,Activa,Sofia Villanueva,0,0,2020-12-22 00:00:00,B3,Hiper,Operaciones Tienda,2.0,3.0,1.0,NaN,NaN

In [34]:
df_dotacion["Dotación Teórica Total"].sum() + df_dotacion["Dotación Real Total"].sum()

np.float64(265726.0)

In [48]:
df_dotacion[["Nombre_Archivo", 'Tipo dotación', 'Formato', 'Ubicación', 'Departamento',
       'Nombre de Posición', 'Categoría', 'Ceco',
       'Fecha', "Dotación Teórica Full", "Dotación Teórica Part", "Dotación Real Full", "Dotación Real Part"]]

id_columns = ["Nombre_Archivo",
        "Tipo dotación",
        "Formato",
        "Ubicación",
        "Departamento",
        "Nombre de Posición",
        "Categoría",
        "Ceco",
    ]

    # Columnas métricas que se colapsarán en una sola dimensión
value_columns = [
       "Dotación Teórica Full",
       "Dotación Teórica Part",
       "Dotación Real Full",
       "Dotación Real Part",
       "Vulnerables Full",
       "Vulnerables Part"
]

# Operación vectorizada de reshaping
df_long = pd.melt(
       df_dotacion,
       id_vars=id_columns,
       value_vars=value_columns,
       var_name="TipoDotacionx",
       value_name="HeadCount",
)

In [49]:
mapeo_dotacion_invertido = {
    "Dotación Real Full": "RealFT",
    "Dotación Real Part": "RealPT",
    "Dotación Teórica Full": "TeoFT",
    "Dotación Teórica Part": "TeoPT",
    "Vulnerables Full": "VulneraFT",
    "Vulnerables Part": "VulneraPT",
}

In [50]:
df_long["TipoDotacion"] = df_long["TipoDotacionx"].map(mapeo_dotacion_invertido)

In [51]:
df_long[df_long["TipoDotacion"].isin(["Dotación Teórica Full", "Dotación Teórica Part"])]["HeadCount"].sum()

np.float64(0.0)

In [54]:
df_long["_JEq"] = np.where(
    df_long["TipoDotacion"].str.contains("FT", na=False),
    df_long["HeadCount"],
    df_long["HeadCount"] / 2,
)

In [55]:
df_long

,Nombre_Archivo,Tipo dotación,Formato,Ubicación,Departamento,Nombre de Posición,Categoría,Ceco,TipoDotacionx,HeadCount,TipoDotacion,_JEq
0,Dotación_FRET_202507.xlsx,Ordinaria,Plaza Vea,Fret Pvea Acho,Administracion,Asistente De Tienda,Medio,Operaciones Tienda,Dotación Teórica Full,1.0,TeoFT,1.0
1,Dotación_FRET_202507.xlsx,Ordinaria,Plaza Vea,Fret Pvea Acho,Administracion,Gerente De Tienda,Lider,Operaciones Tienda,Dotación Teórica Full,1.0,TeoFT,1.0
2,Dotación_FRET_202507.xlsx,Ordinaria,Plaza Vea,Fret Pvea Acho,Administracion,Subgerente De Tienda,Lider,Operaciones Tienda,Dotación Teórica Full,0.0,TeoFT,0.0
3,Dotación_FRET_202507.xlsx,Ordinaria,Plaza Vea,Fret Pvea Acho,Almacen,Jefe De Seccion,Medio,Operaciones Tienda,Dotación Teórica Full,1.0,TeoFT,1.0
4,Dotación_FRET_202507.xlsx,Ordinaria,Plaza Vea,Fret Pvea Acho,Almacen,Repres. De Servicios,Operativo,Operaciones Tienda,Dotación Teórica Full,0.0,TeoFT,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
344545,Dotación_FRET_202606.xlsx,Ordinaria,Plaza Vea,PVO Tarapoto 2,Sala Frescos,Repres. De Servicios,Operativo,Operaciones Tienda,Vulnerables Part,0.0,VulneraPT,0.0
344546,Dotación_FRET_202606.xlsx,Ordinaria,Plaza Vea,PVO Tarapoto 2,Sala Frescos,Repres. De Servicios 5X2,Operativo,Operaciones Tienda,Vulnerables Part,0.0,VulneraPT,0.0
344547,Dotación_FRET_202606.xlsx,Ordinaria,Plaza Vea,PVO Tarapoto 2,Sala Frescos,Repres. De Servicios 5X2 1Er Turno,Operativo,Operaciones Tienda,Vulnerables Part,0.0,VulneraPT,0.0
344548,Dotación_FRET_202606.xlsx,Ordinaria,Plaza Vea,PVO Tarapoto 2,Sala Frescos,Repres. De Servicios 5X2 2Do Turno,Operativo,Operaciones Tienda,Vulnerables Part,0.0,VulneraPT,0.0
344549,Dotación_FRET_202606.xlsx,Ordinaria,Plaza Vea,PVO Tarapoto 2,Sala Frescos,Repres. De Servicios I,Medio,Operaciones Tienda,Vulnerables Part,0.0,VulneraPT,0.0

In [52]:
df_dotacion["Dotación Teórica Full"].sum() + df_dotacion["Dotación Teórica Part"].sum()

np.float64(135097.0)