In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
from glob import glob
# Aplicar configuraciones de visualización total de Pandas
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

from pathlib import Path
import glob

import warnings
warnings.filterwarnings("ignore")
import plotly.express as px

import func_negocio as func

In [2]:
bd_locales = r"input\Productividad 2026 v4 --- ep.xlsx"
df_locales = pd.read_excel(bd_locales, sheet_name="Locales")

In [3]:
bd_2025 = r"input\bd_ventas\Export_VentaProdBI_2025.xlsx"
df_2025 = pd.read_excel(bd_2025)


df_2025["codigo_local"] = df_2025["Codigo Local"]
df_2025["tipo_venta"] = df_2025["Tipo Venta"]
df_2025["nombre_area"] = df_2025["nombre_area"]
df_2025["nombre_division"] = df_2025["nombre_division"]
df_2025["VtaNeta"] = df_2025["VtaNeta"]
df_2025["VtaUnidad"] = df_2025["VtaUnidad"]
df_2025["VtaNetaPpto"] = df_2025["VtaNetaPpto"]

df_2025 = df_2025[~df_2025["nombre_division"].isnull()]

In [4]:
lista_archivos = [
    "Export_VentaProdBI_202601.xlsx",
    "Export_VentaProdBI_202602.xlsx",
    "Export_VentaProdBI_202603.xlsx",
    "Export_EstimarMesActual_20260430.xlsx",
    "Export_EstimarMesActual_202605.xlsx",
    "Export_EstimarMesActual_20260611.xlsx",
]
ruta = r"input\bd_ventas"

rutas_completas = [os.path.join(ruta, archivo) for archivo in lista_archivos]
dfs = [pd.read_excel(p) for p in rutas_completas]
df_2026 = pd.concat(dfs, ignore_index=True)

df_2026["codigo_local"] = df_2026["Codigo Local"]
df_2026["tipo_venta"] = df_2026["Tipo Venta"]
df_2026["nombre_area"] = df_2026["nombre_area"]
df_2026["nombre_division"] = df_2026["nombre_division"]
df_2026["VtaNeta"] = df_2026["VtaNeta"]
df_2026["VtaUnidad"] = df_2026["VtaUnidad"]
df_2026["VtaNetaPpto"] = df_2026["VtaNetaPpto"]

df_2026 = df_2026[~df_2026["nombre_division"].isnull()]
df_2026["Anio"] = df_2026["Anio"].fillna(df_2026["Fecha"].dt.year)
df_2026["NroMes"] = df_2026["NroMes"].fillna(df_2026["Fecha"].dt.month)

In [5]:
df_ventas_all = pd.concat([df_2025, df_2026])

In [10]:
df_ventas_all["Tipo Venta"].unique()

array(['Venta Ecommerce', 'Venta POS', 'Venta CNegocio', 'Delivery',
       'Last Mile'], dtype=object)

In [23]:
df_ventas_all1 = df_ventas_all[df_ventas_all["Tipo Venta"].isin(['Venta Ecommerce', 'Venta POS','Last Mile'])&(df_ventas_all["NroMes"]!=12)]

In [24]:
df_ventas_all1.head(3)

,Tipo Venta,Anio,NroMes,Codigo Local,nombre_division,nombre_area,VtaNeta,VtaUnidad,VtaNetaPpto,codigo_local,tipo_venta,VtaNetaDA,Fecha,codigo_division,codigo_area,VtaNetaFA,VtaUnidadFA,VtaUnidadDA
0,Venta Ecommerce,2025.0,1.0,1198,ABARROTES,BEBIDAS,NaN,NaN,9.3032,1198,Venta Ecommerce,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,Venta POS,2025.0,1.0,1198,ABARROTES,BEBIDAS,212769.88,30106.0,189950.4110,1198,Venta POS,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2,Venta Ecommerce,2025.0,1.0,1198,ABARROTES,COMESTIBLES,NaN,NaN,19.6378,1198,Venta Ecommerce,NaN,NaT,NaN,NaN,NaN,NaN,NaN

In [27]:
df_locales.head(3)

,codigo_local,formato,formato2,ubicacion,nombre,cluster,Cluster Comercial,Cluster NSE,Cluster NSE Comercial,Cluster_Comercial,Metros Cuadrados,Rangom2,TieneDeli,TieneSCO,TieneTextil,regional,supervisor,departamento,provincia,distrito,nombre_Kr,nombre_Dot2-,nombre_Dot,nombre_Fin,GOS,GOR,SSS1,SSS2,SSS,Latitud,Longitud,EsMultif,Local_Disponib,Descripcion_Sede,Gondorack,Centro comercial,Venta Asistida,Carriboys,almacén en subsuelo,Almacén 1er piso,Almacén 2do o 3er piso,Niveles de piso de venta,Montacargas,Stoka,Niveles Rack almacenaje,Rampa mecánica en recepción,Área Electro,Delivea,Tiene Self check out,Producción Propia,Comentario,_Tienda
0,1198,PLAZA VEA,HIPER,Provincia,Cusco Wanchaq - PVH,B2,B2,B,BC,BC2,0,1000-,No,NaN,Si,Sebastián Santangelo,José Aramburu,Cusco,Cusco,Wanchaq,CFR SVEA CUZCO QUOYLLUR,Fret Svea Cuzco Quoyllur,FRET - SVEA CUZCO QUOYLLUR,Cusco Wanchaq - PVH,Sebastián S,José A,2000-01-01,2030-01-01,SSS,-13.520693,-71.972614,Normal,SVEA CUZCO QUOYLLUR,SVEA CUZCO QUOYLLUR,Sí,Sí,No,No,Sí,No,No,1 nivel,Sí,Sí,3,Sí,Sí,No,Sí,SI,solo tenemos de carne molida,1198_Cusco Wanchaq - PVH
1,1199,PLAZA VEA,HIPER,Lima + Callao,San Miguel - PVH,A2,A2,A,BC,BC2,0,1000-,No,NaN,Si,Sebastián Santangelo,José Aramburu,Lima,Lima,San Miguel,CFR SVEA SAN MIGUEL,Fret Svea San Miguel,FRET - SVEA SAN MIGUEL,San Miguel - PVH,Sebastián S,José A,2000-01-01,2030-01-01,SSS,-12.07663,-77.08396,Normal,SVEA SAN MIGUEL,SVEA SAN MIGUEL,No,Sí,Sí,No,No,No,Sí,2 niveles,Sí,Sí,4,Sí,Sí,No,Sí,NO,0,1199_San Miguel - PVH
2,1593,PLAZA VEA,HIPER,Lima + Callao,Aventura SJL - PVH,C3,C3,C,BC,BC3,4136,4000-5000,No,NaN,Si,Sofía Villanueva,Vik Enciso,LIMA,Lima,SAN JUAN DE LURIGANCHO,CFR PVEA AVENTURA SJL,FRET PVEA AVENTURA SJL,FRET - PVEA AVENTURA SJL,Aventura SJL - PVH,Sofía V,Vik E,2000-01-01,2030-01-01,SSS,-12.01409,-76.99881,Normal,PVEA SJ LURIGANCHO,PVEA AVENTURA SJL,Sí,Sí,Sí,No,No,Sí,No,1 nivel,Sí,Sí,4,Sí,Sí,No,Sí,NO,0,1593_Aventura SJL - PVH

In [28]:
df_ventas_all1

df_ventas_all1["codigo_local"] = df_ventas_all1["codigo_local"].astype(str)
df_locales["codigo_local"] = df_locales["codigo_local"].astype(str)

df_fin = df_ventas_all1.merge(df_locales[["codigo_local", "_Tienda", "formato", "formato2", "ubicacion", "regional", "supervisor"]], on="codigo_local", how="inner")

In [39]:
df_ventas_all1

df_fin = df_ventas_all1.merge(df_locales[["codigo_local", "_Tienda", "formato", "formato2", "ubicacion", "regional", "supervisor"]], on="codigo_local", how="inner")

In [ ]:
df_fin[""]

,Tipo Venta,Anio,NroMes,Codigo Local,nombre_division,nombre_area,VtaNeta,VtaUnidad,VtaNetaPpto,codigo_local,tipo_venta,VtaNetaDA,Fecha,codigo_division,codigo_area,VtaNetaFA,VtaUnidadFA,VtaUnidadDA,_Tienda,formato,formato2,ubicacion,regional,supervisor
0,Venta Ecommerce,2025.0,1.0,1198,ABARROTES,BEBIDAS,NaN,NaN,9.3032,1198,Venta Ecommerce,NaN,NaT,NaN,NaN,NaN,NaN,NaN,1198_Cusco Wanchaq - PVH,PLAZA VEA,HIPER,Provincia,Sebastián Santangelo,José Aramburu
1,Venta POS,2025.0,1.0,1198,ABARROTES,BEBIDAS,212769.88,30106.00,189950.4110,1198,Venta POS,NaN,NaT,NaN,NaN,NaN,NaN,NaN,1198_Cusco Wanchaq - PVH,PLAZA VEA,HIPER,Provincia,Sebastián Santangelo,José Aramburu
2,Venta Ecommerce,2025.0,1.0,1198,ABARROTES,COMESTIBLES,NaN,NaN,19.6378,1198,Venta Ecommerce,NaN,NaT,NaN,NaN,NaN,NaN,NaN,1198_Cusco Wanchaq - PVH,PLAZA VEA,HIPER,Provincia,Sebastián Santangelo,José Aramburu
3,Venta POS,2025.0,1.0,1198,ABARROTES,COMESTIBLES,440968.33,79877.00,393016.7022,1198,Venta POS,NaN,NaT,NaN,NaN,NaN,NaN,NaN,1198_Cusco Wanchaq - PVH,PLAZA VEA,HIPER,Provincia,Sebastián Santangelo,José Aramburu
4,Venta POS,2025.0,1.0,1198,ABARROTES,CUIDADO PERSONAL Y LIMPIEZA,394202.26,29990.00,397135.3413,1198,Venta POS,NaN,NaT,NaN,NaN,NaN,NaN,NaN,1198_Cusco Wanchaq - PVH,PLAZA VEA,HIPER,Provincia,Sebastián Santangelo,José Aramburu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257012,Venta POS,2026.0,6.0,X210,FRESCOS,PANADERIA Y PASTELERIA,416.34,77.41,NaN,X210,Venta POS,278.19,2026-06-01,D2,A10,422.70,88.58,62.39,X210_Santa Cruz - PVE,PLAZA VEA EXPRESS,EXPRESS,Lima + Callao,Hernán Perroni,Joe Huamancondor
257013,Venta POS,2026.0,6.0,X210,NON FOOD,ELECTRO,0.00,0.00,NaN,X210,Venta POS,0.00,2026-06-01,D3,A11,4.24,5.00,0.00,X210_Santa Cruz - PVE,PLAZA VEA EXPRESS,EXPRESS,Lima + Callao,Hernán Perroni,Joe Huamancondor
257014,Venta POS,2026.0,6.0,X210,NON FOOD,BAZAR,256.47,49.00,NaN,X210,Venta POS,301.98,2026-06-01,D3,A13,364.88,59.00,54.00,X210_Santa Cruz - PVE,PLAZA VEA EXPRESS,EXPRESS,Lima + Callao,Hernán Perroni,Joe Huamancondor
257015,Venta POS,2026.0,6.0,X210,NON FOOD,HOGAR,45.00,14.00,NaN,X210,Venta POS,180.54,2026-06-01,D3,A15,176.67,31.00,29.00,X210_Santa Cruz - PVE,PLAZA VEA EXPRESS,EXPRESS,Lima + Callao,Hernán Perroni,Joe Huamancondor
257016,Venta POS,2026.0,6.0,X210,MISCELANEOS,MISCELANEOS,50.04,117.00,NaN,X210,Venta POS,25.22,2026-06-01,D4,A14,24.87,84.00,108.00,X210_Santa Cruz - PVE,PLAZA VEA EXPRESS,EXPRESS,Lima + Callao,Hernán Perroni,Joe Huamancondor